// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDILLQd1dQ7MQdwB_vtVU0S-TOkrAlOVIo',
    appId: '1:299057678066:web:8345929fdbf6c58641f26b',
    messagingSenderId: '299057678066',
    projectId: 'the-real-wayt',
    authDomain: 'the-real-wayt.firebaseapp.com',
    storageBucket: 'the-real-wayt.firebasestorage.app',
    measurementId: 'G-HPF8W93LJZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9mctHIS2LT4fcWiuzyIENpH6AkD0XVZY',
    appId: '1:299057678066:android:9fe7ab2052402c8f41f26b',
    messagingSenderId: '299057678066',
    projectId: 'the-real-wayt',
    storageBucket: 'the-real-wayt.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlHaoT52hxiIzFADPmHxBLcrwCfvG9Www',
    appId: '1:299057678066:ios:ee37920355ce0f1f41f26b',
    messagingSenderId: '299057678066',
    projectId: 'the-real-wayt',
    storageBucket: 'the-real-wayt.firebasestorage.app',
    iosBundleId: 'com.example.wayt',
  );

}